version: '3.8'
name: fullstack
services:
  fullstack-db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ../.env
    ports:
      - '3306:3306'
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u user --password=password
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - '../database/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql'
